# Generated by Django 6.0.3 on 2026-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('consejo_comunal', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('vecino', 'Vecino')], default='vecino', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('discapacidad', models.CharField(default='No Posee', max_length=50)),
                ('intentos_recuperacion', models.IntegerField(default=0)),
                ('bloqueo_hasta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Miembro',
        ),
    ]
