# Generated by Django 6.0.3 on 2026-03-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_constancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='anios_residencia',
            field=models.IntegerField(default=1),
        ),
    ]
