# Generated by Django 6.0.3 on 2026-04-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_constancia_anios_residencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('parentesco', models.CharField(choices=[('Hijo/a', 'Hijo/a'), ('Sobrino/a', 'Sobrino/a'), ('Nieto/a', 'Nieto/a'), ('Otro', 'Otro')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=15)),
                ('discapacidad', models.CharField(default='No Posee', max_length=50)),
                ('escolarizado', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2)),
                ('cedula_identidad', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='gestion.usuario')),
            ],
        ),
    ]
