# Generated by Django 6.0.3 on 2026-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cargafamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
